feat(archetype): add archetype for rest service delete
americanexpress/synapse pull request #143
Opened 2022-09-29 15:14 UTC by eaquin02

This PR is for adding the synapse-archetype-service-rest-delete module.

2022-09-29 15:23 UTC, whoswendy requested changes
Please add dependency to main pom.xml and add a __className__Application.java

2022-09-29 18:04 UTC, whoswendy approved these changes

2022-09-29 19:37 UTC, whoswendy commented on archetype/synapse-archetype-service-rest-delete/src/main/resources/archetype-resources/src/main/java/service/__className__DeleteService.java
> +package ${package}.service;
please add copyright

2022-09-29 19:38 UTC, whoswendy requested changes
please add missing copyright

2022-09-29 21:01 UTC, whoswendy approved these changes

2022-09-29 21:07 UTC, guttff commented on archetype/synapse-archetype-service-rest-delete/src/main/resources/archetype-resources/src/main/java/config/__className__DeleteServiceEndpoint.java
> +    /**
add a private contrusctor

2022-09-29 21:08 UTC, guttff commented on archetype/synapse-archetype-service-rest-delete/src/main/resources/archetype-resources/src/test/java/service/__className__DeleteServiceIT.java
> +    void callDeleteService_givenValidRequest_expectedValidResponse() throws Exception {
```suggestion
    void delete_givenValidRequest_expectedValidResponse() throws Exception {
```

2022-09-29 21:09 UTC, guttff commented on archetype/synapse-archetype-service-rest-delete/src/main/resources/archetype-resources/src/test/java/service/__className__DeleteServiceIT.java
> +    void callDeleteService_givenValidRequest_expectedValidResponse() throws Exception {
We should keep the name of the method exactly how the actual method is named

2022-09-30 19:03 UTC, guttff approved these changes

2022-09-30 19:03 UTC, merged