Feature/synapse service mongodb sample
americanexpress/synapse pull request #144
Opened 2022-09-29 16:21 UTC by whoswendy

This PR includes sample for end to end integration with service-rest and data-mongodb.

2022-09-30 15:32 UTC, guttff requested changes

2022-09-30 15:32 UTC, guttff commented on service/service-samples/pom.xml
> +<!--        <module>sample-service-rest-native-book</module>-->
remove commented code

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/ReactiveDeleteBookService.java
> +    protected Mono<Void> executeDelete(String identifier) {
I know we have identifier as the default naming of the string. Can we instead call this String "title."

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/controller/DeleteBookReactiveController.java
> +package io.americanexpress.service.book.rest.controller;
Add Copyright

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/controller/UpdateBookReactiveController.java
> +package io.americanexpress.service.book.rest.controller;
Add Copyright

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/CreateBookRequest.java
> +    public void setTitle(String title) {
add java docs on getter & setter

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/ReadBookRequest.java
> +    public String getTitle() {
add java doc on getter & setter

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/ReadBookResponse.java
> +    public void setTitle(String title) {
add javadoc on getter & setter

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/UpdateBookRequest.java
> +    public String getTitle() {
Add javadoc on getter & setter

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/CreateBookReactiveService.java
> +    protected Mono<CreateBookResponse> executeCreate(CreateBookRequest request) {
Add javadoc on method

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/DeleteBookReactiveService.java
> +    protected Mono<Void> executeDelete(String title) {
Add javadoc

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/ReadPolyBookReactiveService.java
> +    protected Flux<ReadBookResponse> executeRead(ReadBookRequest request) {
Add javadoc

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/UpdateBookReactiveService.java
> +    protected Mono<Void> executeUpdate(UpdateBookRequest request) {
Add javadoc

2022-10-12 15:27 UTC, andCastStatic commented on data/data-samples/sample-data-mongodb-reactive/src/main/java/io/americanexpress/data/book/entity/BookEntity.java
> +
add javadoc to getter & setters

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/config/BookConfig.java
> +    public BookConfig() {}
is this constructor needed?

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/resources/service-book-application.properties
> +wavefront.application.service=example-service-rest-book
add line eof

2022-10-12 15:27 UTC, andCastStatic commented on data/data-samples/sample-data-mongodb-reactive/src/main/java/io/americanexpress/data/book/entity/BookEntity.java
> +    }
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on data/data-samples/sample-data-mongodb-reactive/src/main/java/io/americanexpress/data/book/repository/BookRepository.java
>  }
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/BookApplication.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/config/BookConfig.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/config/BookEndpoints.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/controller/CreateBookReactiveController.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/controller/DeleteBookReactiveController.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/controller/ReadPolyBookReactiveController.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/controller/UpdateBookReactiveController.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/CreateBookRequest.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/CreateBookResponse.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/ReadBookRequest.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/ReadBookResponse.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/model/UpdateBookRequest.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/CreateBookReactiveService.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/DeleteBookReactiveService.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/ReadPolyBookReactiveService.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/UpdateBookReactiveService.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/service/helper/ReadBookResponseCreator.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/test/java/io/americanexpress/service/book/rest/config/BookTestConfig.java
> +}
EOF line needed

2022-10-12 15:27 UTC, andCastStatic commented on service/service-samples/sample-service-rest-mongodb-book/src/test/java/io/americanexpress/service/book/rest/service/helper/ReadBookResponseCreatorTest.java
> +}
EOF line needed

2022-10-12 15:34 UTC, whoswendy commented on service/service-samples/sample-service-rest-mongodb-book/src/main/java/io/americanexpress/service/book/rest/config/BookConfig.java
> +    public BookConfig() {}
removed

2022-12-07 21:21 UTC, guttff approved these changes

2022-12-07 21:21 UTC, guttff commented on service/service-samples/sample-service-rest-mongodb-book/src/test/java/io/americanexpress/service/book/rest/service/helper/ReadBookResponseCreatorTest.java
> +
remove extra line

2022-12-07 21:21 UTC, merged