Feature/synapse data mssql just reactive
americanexpress/synapse pull request #250
Opened 2023-06-08 18:01 UTC by whoswendy

This PR contains code to add a synapse-data-mssql module that provides reactive support connecting to Microsoft SQL database.

2023-06-08 19:39 UTC, andCastStatic requested changes

2023-06-08 19:39 UTC, andCastStatic commented on data/data-samples/sample-data-mssql-reactive-book/src/main/java/io/americanexpress/data/book/entity/BookEntity.java
> +    private String author;
May we add java docs here?

2023-06-08 19:39 UTC, andCastStatic commented on data/data-samples/sample-data-mssql-reactive-book/src/main/resources/schema.sql
> +USE tempdb;
add copy right here

2023-06-08 19:39 UTC, andCastStatic commented on data/data-samples/sample-data-mssql-reactive-book/src/main/resources/schema.sql
> +GO
add line eof

2023-06-12 13:24 UTC, whoswendy commented on data/data-samples/sample-data-mssql-reactive-book/src/main/resources/schema.sql
> +USE tempdb;
done

2023-06-12 13:24 UTC, whoswendy commented on data/data-samples/sample-data-mssql-reactive-book/src/main/java/io/americanexpress/data/book/entity/BookEntity.java
> +    private String author;
done

2023-06-16 16:04 UTC, merged