add database name to property file
americanexpress/synapse pull request #319
Opened 2024-12-02 19:00 UTC by brenoreis

This PR adds a database name to the cassandra db properties.
It will be useful when one app needs to connect to 2 different cassandra dbs.

2024-12-02 19:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/americanexpress/synapse?pullRequest=319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/americanexpress/synapse?pullRequest=319) before we can accept your contribution.<br/><hr/>**breisalm** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/americanexpress/synapse?pullRequest=319) it.</sub>

2024-12-04 19:24 UTC, LuisDiaz79 approved these changes

2024-12-04 20:23 UTC, adgonz90 approved these changes

2024-12-04 20:23 UTC, adgonz90 requested changes
Please update the docs

2024-12-04 21:00 UTC, adgonz90 approved these changes

2024-12-04 21:00 UTC, merged