Feature/add some sample data postgres
americanexpress/synapse pull request #64
Opened 2022-04-01 19:05 UTC by amorgado

-  Added the example-data-postgres-book in order to have some data sample application that uses the synapse-data-postgres module and give an example of how to use it (It will be improved in the future with unit tests and other things).
- Added a schema.sql, data.sql, book entity and book repository for the book table to this new module.
- Upgraded H2 and Postgres Jars and tested with the new example-data-postgres-book recently created.

2022-04-01 19:16 UTC, jmartinez5120 requested changes
We need to add Copyrights to all classes. You can copy paste from others.

2022-04-01 19:19 UTC, jmartinez5120 requested changes
Please check comments.

2022-04-01 19:19 UTC, jmartinez5120 commented on data/example-data-postgres-book/src/main/java/io/americanexpress/data/book/DataBookApplication.java
> +@EnableConfigurationProperties
I don't think we need `@EnableConfigurationProperties`. I believe `@SpringBootApplication` already has it by default.

2022-04-01 19:19 UTC, jmartinez5120 commented on data/example-data-postgres-book/src/main/java/io/americanexpress/data/book/entity/BookEntity.java
> +    private String getTitle() {
`getTitle()` doesn't have JavaDocs

2022-04-01 19:24 UTC, cuztomizer approved these changes

2022-04-04 20:03 UTC, jmartinez5120 requested changes
This pom file is missing copyrights. Please add them and we should be good to approve.
`data/example-data-postgres-book/pom.xml`

2022-04-04 20:03 UTC, jmartinez5120 commented on data/example-data-postgres-book/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
We need to add copyrights in this pom file.

2022-04-04 21:24 UTC, jmartinez5120 approved these changes
LGTM

2022-04-04 21:24 UTC, jmartinez5120 commented on data/example-data-postgres-book/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Done

2022-04-04 21:27 UTC, merged